# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger docs for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyroyale
from pyroyale.models.player_ranking_list_items import PlayerRankingListItems  # noqa: E501
from pyroyale.rest import ApiException


class TestPlayerRankingListItems(unittest.TestCase):
    """PlayerRankingListItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerRankingListItems(self):
        """Test PlayerRankingListItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyroyale.models.player_ranking_list_items.PlayerRankingListItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
