# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger docs for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import io
import sys
import unittest

import pyroyale
from pyroyale.models.war_log import WarLog  # noqa: E501
from pyroyale.rest import ApiException


class TestWarLog(unittest.TestCase):
    """WarLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWarLog(self):
        """Test WarLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WarLog()  # noqa: E501
        pass

    def testDefaults(self):
        model = WarLog()
        pass

    def testConstructorInitializers(self):
        model = WarLog(
            items='items'
        )

        assert model.items=='items'

    def testToDict(self):
        model = WarLog(
            items='items'
        )
        modelDict = model.to_dict()

        assert modelDict['items']=='items'

        model = WarLog(
            items=123,
        )
        modelDict = model.to_dict()

        assert modelDict['items']==123

        model = WarLog(
            items=[WarLog(items='items')],
        )
        modelDict = model.to_dict()

        assert modelDict['items'][0]['items']=='items'

    def testToString(self):
        model = WarLog('TestStringSequence')

        modelString = model.to_str()
        assert len(modelString) > 1
        assert 'TestStringSequence' in modelString

    def testPrint(self):
        model = WarLog('TestStringSequence')

        capturedOutput = io.StringIO()
        sys.stdout = capturedOutput
        print(model)
        sys.stdout = sys.__stdout__

        testString = capturedOutput.getvalue()

        assert len(testString) > 1
        assert 'TestStringSequence' in testString


    def testEqual(self):
        model_a  = WarLog('A')
        model_a2 = WarLog('A')
        model_b  = WarLog('B')

        assert model_a == model_a
        assert model_a == model_a2
        assert model_a != model_b
        assert model_a != 'not a'


if __name__ == '__main__':
    unittest.main()
