# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger docs for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyroyale
from pyroyale.models.player_detail_league_statistics import PlayerDetailLeagueStatistics  # noqa: E501
from pyroyale.rest import ApiException


class TestPlayerDetailLeagueStatistics(unittest.TestCase):
    """PlayerDetailLeagueStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerDetailLeagueStatistics(self):
        """Test PlayerDetailLeagueStatistics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyroyale.models.player_detail_league_statistics.PlayerDetailLeagueStatistics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
