# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger docs for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyroyale
from pyroyale.api.cards_api import CardsApi  # noqa: E501
from pyroyale.rest import ApiException


class TestCardsApi(unittest.TestCase):
    """CardsApi unit test stubs"""

    def setUp(self):
        self.api = CardsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cards(self):
        """Test case for get_cards

        Get list of available cards  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
