# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger docs for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyroyale
from pyroyale.models.tournament_members_list import TournamentMembersList  # noqa: E501
from pyroyale.rest import ApiException


class TestTournamentMembersList(unittest.TestCase):
    """TournamentMembersList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTournamentMembersList(self):
        """Test TournamentMembersList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyroyale.models.tournament_members_list.TournamentMembersList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
