# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger docs for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyroyale
from pyroyale.api.tournaments_api import TournamentsApi  # noqa: E501
from pyroyale.rest import ApiException


class TestTournamentsApi(unittest.TestCase):
    """TournamentsApi unit test stubs"""

    def setUp(self):
        self.api = TournamentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_global_tournaments(self):
        """Test case for get_global_tournaments

        List global tournaments  # noqa: E501
        """
        pass

    def test_get_tournament(self):
        """Test case for get_tournament

        Get tournament information  # noqa: E501
        """
        pass

    def test_search_tournaments(self):
        """Test case for search_tournaments

        Search tournaments  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
