# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger docs for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyroyale
from pyroyale.models.upcoming_chests_list import UpcomingChestsList  # noqa: E501
from pyroyale.rest import ApiException


class TestUpcomingChestsList(unittest.TestCase):
    """UpcomingChestsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpcomingChestsList(self):
        """Test UpcomingChestsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyroyale.models.upcoming_chests_list.UpcomingChestsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
