# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger docs for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest
from unittest.mock import patch

import pyroyale
from pyroyale.api.clans_api import ClansApi  # noqa: E501
from pyroyale.rest import ApiException


class TestClansApi(unittest.TestCase):
    """ClansApi unit test stubs"""

    def setUp(self):
        self.api = ClansApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_clan(self):
        """Test case for get_clan

        Get clan information  # noqa: E501
        """
        pass

    def test_get_clan_members(self):
        """Test case for get_clan_members

        List clan members  # noqa: E501
        """
        pass

    def test_get_clan_war_log(self):
        """Test case for get_clan_war_log

        Retrieve clan's clan war log  # noqa: E501
        """
        pass

    def test_get_current_war(self):
        """Test case for get_current_war

        Information about clan's current clan war  # noqa: E501
        """
        pass

    def test_search_clans(self):
        """Test case for search_clans

        Search clans  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
