# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger definition for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import io
import sys
import unittest

import pyroyale
from pyroyale.models.battle_log_game_mode import BattleLogGameMode  # noqa: E501
from pyroyale.rest import ApiException


class TestBattleLogGameMode(unittest.TestCase):
    """BattleLogGameMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBattleLogGameMode(self):
        """Test BattleLogGameMode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyroyale.models.battle_log_game_mode.BattleLogGameMode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
