# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger definition for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyroyale
from models.player_achievement import PlayerAchievement  # noqa: E501
from pyroyale.rest import ApiException


class TestPlayerAchievement(unittest.TestCase):
    """PlayerAchievement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerAchievement(self):
        """Test PlayerAchievement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyroyale.models.player_achievement.PlayerAchievement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
