# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger docs for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyroyale
from pyroyale.models.player_ranking_list import PlayerRankingList  # noqa: E501
from pyroyale.rest import ApiException


class TestPlayerRankingList(unittest.TestCase):
    """PlayerRankingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerRankingList(self):
        """Test PlayerRankingList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyroyale.models.player_ranking_list.PlayerRankingList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
