# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger definition for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import io
import sys
import unittest

import pyroyale
from pyroyale.models.game_mode import GameMode  # noqa: E501
from pyroyale.rest import ApiException


class TestGameMode(unittest.TestCase):
    """GameMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDefaults(self):
        model = GameMode()
        pass

    def testConstructorInitializers(self):
        model = GameMode(
            id='id',
            name='name'
        )

        assert model.id=='id'
        assert model.name=='name'

    def testToDict(self):
        model = GameMode(
            id=GameMode(id='id', name=123),
            name=[GameMode(id={'foo': 'bar'})]
        )
        modelDict = model.to_dict()

        assert modelDict['id']['id']=='id'
        assert modelDict['id']['name']==123
        assert modelDict['name'][0]['id']['foo']=='bar'

    def testToString(self):
        model = GameMode('TestStringSequence')

        modelString = model.to_str()
        assert len(modelString) > 1
        assert 'TestStringSequence' in modelString

    def testPrint(self):
        model = GameMode('TestStringSequence')

        capturedOutput = io.StringIO()
        sys.stdout = capturedOutput
        print(model)
        sys.stdout = sys.__stdout__

        testString = capturedOutput.getvalue()

        assert len(testString) > 1
        assert 'TestStringSequence' in testString


    def testEqual(self):
        model_a  = GameMode('A')
        model_a2 = GameMode('A')
        model_b  = GameMode('B')

        assert model_a == model_a
        assert model_a == model_a2
        assert model_a != model_b
        assert model_a != 'not a'

if __name__ == '__main__':
    unittest.main()
