# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger definition for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyroyale
from pyroyale.models.player_ranked import PlayerRanked  # noqa: E501
from pyroyale.rest import ApiException


class TestPlayerRanked(unittest.TestCase):
    """PlayerRanked unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerRanked(self):
        """Test PlayerRanked"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyroyale.models.player_ranked.PlayerRanked()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
