# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger docs for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyroyale
from pyroyale.models.tournament import Tournament  # noqa: E501
from pyroyale.rest import ApiException


class TestTournament(unittest.TestCase):
    """Tournament unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTournament(self):
        """Test Tournament"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Tournament()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
