# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger definition for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pyroyale
from pyroyale.models.tournament_player import TournamentPlayer  # noqa: E501
from pyroyale.rest import ApiException


class TestTournamentPlayer(unittest.TestCase):
    """TournamentPlayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTournamentPlayer(self):
        """Test TournamentPlayer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TournamentPlayer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
