# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger docs for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import io
import sys
import unittest

import pyroyale
from pyroyale.models.location import Location  # noqa: E501
from pyroyale.rest import ApiException


class TestLocation(unittest.TestCase):
    """Location unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocation(self):
        """Test Location"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Location()  # noqa: E501
        pass

    def testDefaults(self):
        model = Location()
        pass

    def testConstructorInitializers(self):
        model = Location(
            id='id',
            name='name',
            country_code='country_code',
            is_country='is_country'
        )

        assert model.id=='id'
        assert model.name=='name'
        assert model.country_code=='country_code'
        assert model.is_country=='is_country'

    def testToDict(self):
        model = Location(
            id={'foo':'bar'},
            name=Location(id=123),
            is_country=[Location(name='clanname')]
        )

        modelDict = model.to_dict()

        assert modelDict['id']['foo']=='bar'
        assert modelDict['name']['id']==123
        assert modelDict['is_country'][0]['name']=='clanname'

    def testToString(self):
        model = Location('TestStringSequence')

        modelString = model.to_str()
        assert len(modelString) > 1
        assert 'TestStringSequence' in modelString

    def testPrint(self):
        model = Location('TestStringSequence')

        capturedOutput = io.StringIO()
        sys.stdout = capturedOutput
        print(model)
        sys.stdout = sys.__stdout__

        testString = capturedOutput.getvalue()

        assert len(testString) > 1
        assert 'TestStringSequence' in testString


    def testEqual(self):
        model_a  = Location('A')
        model_a2 = Location('A')
        model_b  = Location('B')

        assert model_a == model_a
        assert model_a == model_a2
        assert model_a != model_b
        assert model_a != 'not a'


if __name__ == '__main__':
    unittest.main()
