# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger definition for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import io
import sys
import unittest

import pyroyale
from pyroyale.models.search_paging import SearchPaging  # noqa: E501
from pyroyale.rest import ApiException


class TestSearchPaging(unittest.TestCase):
    """SearchPaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConstructorInitializers(self):
        model = SearchPaging(
            cursors='cursors'
        )

        assert model.cursors=='cursors'

    def testToDict(self):
        model = SearchPaging(
            cursors='cursors'
        )
        modelDict = model.to_dict()
        assert modelDict['cursors']=='cursors'

        model = SearchPaging(
            cursors=123,
        )
        modelDict = model.to_dict()
        assert modelDict['cursors']==123

        model = SearchPaging(
            cursors={'foo': 'bar'},
        )
        modelDict = model.to_dict()
        assert modelDict['cursors']['foo']=='bar'

        model = SearchPaging(
            cursors=SearchPaging(cursors='cursors'),
        )
        modelDict = model.to_dict()
        assert modelDict['cursors']['cursors']=='cursors'

        model = SearchPaging(
            cursors=[SearchPaging(cursors='cursors')],
        )
        modelDict = model.to_dict()
        assert modelDict['cursors'][0]['cursors']=='cursors'

    def testToString(self):
        model = SearchPaging('TestStringSequence')

        modelString = model.to_str()
        assert len(modelString) > 1
        assert 'TestStringSequence' in modelString

    def testPrint(self):
        model = SearchPaging('TestStringSequence')

        capturedOutput = io.StringIO()
        sys.stdout = capturedOutput
        print(model)
        sys.stdout = sys.__stdout__

        testString = capturedOutput.getvalue()

        assert len(testString) > 1
        assert 'TestStringSequence' in testString


    def testEqual(self):
        model_a  = SearchPaging('A')
        model_a2 = SearchPaging('A')
        model_b  = SearchPaging('B')

        assert model_a == model_a
        assert model_a == model_a2
        assert model_a != model_b
        assert model_a != 'not a'


if __name__ == '__main__':
    unittest.main()
