# coding: utf-8

# flake8: noqa
"""
    Clash Royale API

    Unofficial Swagger definition for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from pyroyale.models.arena import Arena
from pyroyale.models.battle_log import BattleLog
from pyroyale.models.battle_log_inner import BattleLogInner
from pyroyale.models.battle_log_inner_game_mode import BattleLogInnerGameMode
from pyroyale.models.battle_log_team import BattleLogTeam
from pyroyale.models.battle_log_team_cards import BattleLogTeamCards
from pyroyale.models.card_list import CardList
from pyroyale.models.clan import Clan
from pyroyale.models.clan_base import ClanBase
from pyroyale.models.clan_member import ClanMember
from pyroyale.models.clan_member_list import ClanMemberList
from pyroyale.models.clan_ranking_list import ClanRankingList
from pyroyale.models.clan_ranking_list_items import ClanRankingListItems
from pyroyale.models.clan_search_result import ClanSearchResult
from pyroyale.models.clan_wars_ranking_list import ClanWarsRankingList
from pyroyale.models.current_war import CurrentWar
from pyroyale.models.current_war_clan import CurrentWarClan
from pyroyale.models.error import Error
from pyroyale.models.location import Location
from pyroyale.models.location_list import LocationList
from pyroyale.models.player_base import PlayerBase
from pyroyale.models.player_detail import PlayerDetail
from pyroyale.models.player_detail_achievements import PlayerDetailAchievements
from pyroyale.models.player_detail_cards import PlayerDetailCards
from pyroyale.models.player_detail_current_favourite_card import PlayerDetailCurrentFavouriteCard
from pyroyale.models.player_detail_icon_urls import PlayerDetailIconUrls
from pyroyale.models.player_detail_league_statistics import PlayerDetailLeagueStatistics
from pyroyale.models.player_ranking_list import PlayerRankingList
from pyroyale.models.player_ranking_list_items import PlayerRankingListItems
from pyroyale.models.search_result_clan import SearchResultClan
from pyroyale.models.season_statistics import SeasonStatistics
from pyroyale.models.tournament import Tournament
from pyroyale.models.tournament_base import TournamentBase
from pyroyale.models.tournament_base_items import TournamentBaseItems
from pyroyale.models.tournament_members_list import TournamentMembersList
from pyroyale.models.tournament_search_result import TournamentSearchResult
from pyroyale.models.upcoming_chests_list import UpcomingChestsList
from pyroyale.models.upcoming_chests_list_items import UpcomingChestsListItems
from pyroyale.models.war_clan import WarClan
from pyroyale.models.war_log import WarLog
from pyroyale.models.war_log_items import WarLogItems
from pyroyale.models.war_participant import WarParticipant
from pyroyale.models.war_standing import WarStanding
from pyroyale.models.war_standing_clan import WarStandingClan
