# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger definition for the official Clash Royale API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ClanMember(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'tag': 'str',
        'name': 'str',
        'exp_level': 'int',
        'trophies': 'int',
        'arena': 'Arena',
        'role': 'str',
        'last_seen': 'str',
        'clan_rank': 'int',
        'previous_clan_rank': 'int',
        'donations': 'int',
        'donations_received': 'int',
        'clan_chest_points': 'int'
    }

    attribute_map = {
        'tag': 'tag',
        'name': 'name',
        'exp_level': 'expLevel',
        'trophies': 'trophies',
        'arena': 'arena',
        'role': 'role',
        'last_seen': 'lastSeen',
        'clan_rank': 'clanRank',
        'previous_clan_rank': 'previousClanRank',
        'donations': 'donations',
        'donations_received': 'donationsReceived',
        'clan_chest_points': 'clanChestPoints'
    }

    def __init__(self, tag=None, name=None, exp_level=None, trophies=None, arena=None, role=None, last_seen=None, clan_rank=None, previous_clan_rank=None, donations=None, donations_received=None, clan_chest_points=None):  # noqa: E501
        """ClanMember - a model defined in OpenAPI"""  # noqa: E501

        self._tag = None
        self._name = None
        self._exp_level = None
        self._trophies = None
        self._arena = None
        self._role = None
        self._last_seen = None
        self._clan_rank = None
        self._previous_clan_rank = None
        self._donations = None
        self._donations_received = None
        self._clan_chest_points = None
        self.discriminator = None

        if tag is not None:
            self.tag = tag
        if name is not None:
            self.name = name
        if exp_level is not None:
            self.exp_level = exp_level
        if trophies is not None:
            self.trophies = trophies
        if arena is not None:
            self.arena = arena
        if role is not None:
            self.role = role
        if last_seen is not None:
            self.last_seen = last_seen
        if clan_rank is not None:
            self.clan_rank = clan_rank
        if previous_clan_rank is not None:
            self.previous_clan_rank = previous_clan_rank
        if donations is not None:
            self.donations = donations
        if donations_received is not None:
            self.donations_received = donations_received
        if clan_chest_points is not None:
            self.clan_chest_points = clan_chest_points

    @property
    def tag(self):
        """Gets the tag of this ClanMember.  # noqa: E501


        :return: The tag of this ClanMember.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this ClanMember.


        :param tag: The tag of this ClanMember.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def name(self):
        """Gets the name of this ClanMember.  # noqa: E501


        :return: The name of this ClanMember.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ClanMember.


        :param name: The name of this ClanMember.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def exp_level(self):
        """Gets the exp_level of this ClanMember.  # noqa: E501


        :return: The exp_level of this ClanMember.  # noqa: E501
        :rtype: int
        """
        return self._exp_level

    @exp_level.setter
    def exp_level(self, exp_level):
        """Sets the exp_level of this ClanMember.


        :param exp_level: The exp_level of this ClanMember.  # noqa: E501
        :type: int
        """

        self._exp_level = exp_level

    @property
    def trophies(self):
        """Gets the trophies of this ClanMember.  # noqa: E501


        :return: The trophies of this ClanMember.  # noqa: E501
        :rtype: int
        """
        return self._trophies

    @trophies.setter
    def trophies(self, trophies):
        """Sets the trophies of this ClanMember.


        :param trophies: The trophies of this ClanMember.  # noqa: E501
        :type: int
        """

        self._trophies = trophies

    @property
    def arena(self):
        """Gets the arena of this ClanMember.  # noqa: E501


        :return: The arena of this ClanMember.  # noqa: E501
        :rtype: Arena
        """
        return self._arena

    @arena.setter
    def arena(self, arena):
        """Sets the arena of this ClanMember.


        :param arena: The arena of this ClanMember.  # noqa: E501
        :type: Arena
        """

        self._arena = arena

    @property
    def role(self):
        """Gets the role of this ClanMember.  # noqa: E501


        :return: The role of this ClanMember.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this ClanMember.


        :param role: The role of this ClanMember.  # noqa: E501
        :type: str
        """

        self._role = role

    @property
    def last_seen(self):
        """Gets the last_seen of this ClanMember.  # noqa: E501


        :return: The last_seen of this ClanMember.  # noqa: E501
        :rtype: str
        """
        return self._last_seen

    @last_seen.setter
    def last_seen(self, last_seen):
        """Sets the last_seen of this ClanMember.


        :param last_seen: The last_seen of this ClanMember.  # noqa: E501
        :type: str
        """

        self._last_seen = last_seen

    @property
    def clan_rank(self):
        """Gets the clan_rank of this ClanMember.  # noqa: E501


        :return: The clan_rank of this ClanMember.  # noqa: E501
        :rtype: int
        """
        return self._clan_rank

    @clan_rank.setter
    def clan_rank(self, clan_rank):
        """Sets the clan_rank of this ClanMember.


        :param clan_rank: The clan_rank of this ClanMember.  # noqa: E501
        :type: int
        """

        self._clan_rank = clan_rank

    @property
    def previous_clan_rank(self):
        """Gets the previous_clan_rank of this ClanMember.  # noqa: E501


        :return: The previous_clan_rank of this ClanMember.  # noqa: E501
        :rtype: int
        """
        return self._previous_clan_rank

    @previous_clan_rank.setter
    def previous_clan_rank(self, previous_clan_rank):
        """Sets the previous_clan_rank of this ClanMember.


        :param previous_clan_rank: The previous_clan_rank of this ClanMember.  # noqa: E501
        :type: int
        """

        self._previous_clan_rank = previous_clan_rank

    @property
    def donations(self):
        """Gets the donations of this ClanMember.  # noqa: E501


        :return: The donations of this ClanMember.  # noqa: E501
        :rtype: int
        """
        return self._donations

    @donations.setter
    def donations(self, donations):
        """Sets the donations of this ClanMember.


        :param donations: The donations of this ClanMember.  # noqa: E501
        :type: int
        """

        self._donations = donations

    @property
    def donations_received(self):
        """Gets the donations_received of this ClanMember.  # noqa: E501


        :return: The donations_received of this ClanMember.  # noqa: E501
        :rtype: int
        """
        return self._donations_received

    @donations_received.setter
    def donations_received(self, donations_received):
        """Sets the donations_received of this ClanMember.


        :param donations_received: The donations_received of this ClanMember.  # noqa: E501
        :type: int
        """

        self._donations_received = donations_received

    @property
    def clan_chest_points(self):
        """Gets the clan_chest_points of this ClanMember.  # noqa: E501


        :return: The clan_chest_points of this ClanMember.  # noqa: E501
        :rtype: int
        """
        return self._clan_chest_points

    @clan_chest_points.setter
    def clan_chest_points(self, clan_chest_points):
        """Sets the clan_chest_points of this ClanMember.


        :param clan_chest_points: The clan_chest_points of this ClanMember.  # noqa: E501
        :type: int
        """

        self._clan_chest_points = clan_chest_points

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClanMember):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
