# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger docs for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from pyroyale.models.season_statistics import SeasonStatistics  # noqa: F401,E501


class PlayerDetailLeagueStatistics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'current_season': 'SeasonStatistics',
        'previous_season': 'SeasonStatistics',
        'best_season': 'SeasonStatistics'
    }

    attribute_map = {
        'current_season': 'currentSeason',
        'previous_season': 'previousSeason',
        'best_season': 'bestSeason'
    }

    def __init__(self, current_season=None, previous_season=None, best_season=None):  # noqa: E501
        """PlayerDetailLeagueStatistics - a model defined in Swagger"""  # noqa: E501
        self._current_season = None
        self._previous_season = None
        self._best_season = None
        self.discriminator = None
        if current_season is not None:
            self.current_season = current_season
        if previous_season is not None:
            self.previous_season = previous_season
        if best_season is not None:
            self.best_season = best_season

    @property
    def current_season(self):
        """Gets the current_season of this PlayerDetailLeagueStatistics.  # noqa: E501


        :return: The current_season of this PlayerDetailLeagueStatistics.  # noqa: E501
        :rtype: SeasonStatistics
        """
        return self._current_season

    @current_season.setter
    def current_season(self, current_season):
        """Sets the current_season of this PlayerDetailLeagueStatistics.


        :param current_season: The current_season of this PlayerDetailLeagueStatistics.  # noqa: E501
        :type: SeasonStatistics
        """

        self._current_season = current_season

    @property
    def previous_season(self):
        """Gets the previous_season of this PlayerDetailLeagueStatistics.  # noqa: E501


        :return: The previous_season of this PlayerDetailLeagueStatistics.  # noqa: E501
        :rtype: SeasonStatistics
        """
        return self._previous_season

    @previous_season.setter
    def previous_season(self, previous_season):
        """Sets the previous_season of this PlayerDetailLeagueStatistics.


        :param previous_season: The previous_season of this PlayerDetailLeagueStatistics.  # noqa: E501
        :type: SeasonStatistics
        """

        self._previous_season = previous_season

    @property
    def best_season(self):
        """Gets the best_season of this PlayerDetailLeagueStatistics.  # noqa: E501


        :return: The best_season of this PlayerDetailLeagueStatistics.  # noqa: E501
        :rtype: SeasonStatistics
        """
        return self._best_season

    @best_season.setter
    def best_season(self, best_season):
        """Sets the best_season of this PlayerDetailLeagueStatistics.


        :param best_season: The best_season of this PlayerDetailLeagueStatistics.  # noqa: E501
        :type: SeasonStatistics
        """

        self._best_season = best_season

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlayerDetailLeagueStatistics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlayerDetailLeagueStatistics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
