# coding: utf-8

"""
    Clash Royale API

    Unofficial Swagger docs for the official Clash Royale API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TournamentBaseItems(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tag': 'str',
        'type': 'str',
        'status': 'str',
        'creator_tag': 'str',
        'name': 'str',
        'description': 'str',
        'capacity': 'int',
        'max_capacity': 'int',
        'preparation_duration': 'int',
        'duration': 'int',
        'created_time': 'str'
    }

    attribute_map = {
        'tag': 'tag',
        'type': 'type',
        'status': 'status',
        'creator_tag': 'creatorTag',
        'name': 'name',
        'description': 'description',
        'capacity': 'capacity',
        'max_capacity': 'maxCapacity',
        'preparation_duration': 'preparationDuration',
        'duration': 'duration',
        'created_time': 'createdTime'
    }

    def __init__(self, tag=None, type=None, status=None, creator_tag=None, name=None, description=None, capacity=None, max_capacity=None, preparation_duration=None, duration=None, created_time=None):  # noqa: E501
        """TournamentBaseItems - a model defined in Swagger"""  # noqa: E501
        self._tag = None
        self._type = None
        self._status = None
        self._creator_tag = None
        self._name = None
        self._description = None
        self._capacity = None
        self._max_capacity = None
        self._preparation_duration = None
        self._duration = None
        self._created_time = None
        self.discriminator = None
        if tag is not None:
            self.tag = tag
        if type is not None:
            self.type = type
        if status is not None:
            self.status = status
        if creator_tag is not None:
            self.creator_tag = creator_tag
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if capacity is not None:
            self.capacity = capacity
        if max_capacity is not None:
            self.max_capacity = max_capacity
        if preparation_duration is not None:
            self.preparation_duration = preparation_duration
        if duration is not None:
            self.duration = duration
        if created_time is not None:
            self.created_time = created_time

    @property
    def tag(self):
        """Gets the tag of this TournamentBaseItems.  # noqa: E501


        :return: The tag of this TournamentBaseItems.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this TournamentBaseItems.


        :param tag: The tag of this TournamentBaseItems.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def type(self):
        """Gets the type of this TournamentBaseItems.  # noqa: E501


        :return: The type of this TournamentBaseItems.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TournamentBaseItems.


        :param type: The type of this TournamentBaseItems.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def status(self):
        """Gets the status of this TournamentBaseItems.  # noqa: E501


        :return: The status of this TournamentBaseItems.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TournamentBaseItems.


        :param status: The status of this TournamentBaseItems.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def creator_tag(self):
        """Gets the creator_tag of this TournamentBaseItems.  # noqa: E501


        :return: The creator_tag of this TournamentBaseItems.  # noqa: E501
        :rtype: str
        """
        return self._creator_tag

    @creator_tag.setter
    def creator_tag(self, creator_tag):
        """Sets the creator_tag of this TournamentBaseItems.


        :param creator_tag: The creator_tag of this TournamentBaseItems.  # noqa: E501
        :type: str
        """

        self._creator_tag = creator_tag

    @property
    def name(self):
        """Gets the name of this TournamentBaseItems.  # noqa: E501


        :return: The name of this TournamentBaseItems.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TournamentBaseItems.


        :param name: The name of this TournamentBaseItems.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this TournamentBaseItems.  # noqa: E501


        :return: The description of this TournamentBaseItems.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TournamentBaseItems.


        :param description: The description of this TournamentBaseItems.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def capacity(self):
        """Gets the capacity of this TournamentBaseItems.  # noqa: E501


        :return: The capacity of this TournamentBaseItems.  # noqa: E501
        :rtype: int
        """
        return self._capacity

    @capacity.setter
    def capacity(self, capacity):
        """Sets the capacity of this TournamentBaseItems.


        :param capacity: The capacity of this TournamentBaseItems.  # noqa: E501
        :type: int
        """

        self._capacity = capacity

    @property
    def max_capacity(self):
        """Gets the max_capacity of this TournamentBaseItems.  # noqa: E501


        :return: The max_capacity of this TournamentBaseItems.  # noqa: E501
        :rtype: int
        """
        return self._max_capacity

    @max_capacity.setter
    def max_capacity(self, max_capacity):
        """Sets the max_capacity of this TournamentBaseItems.


        :param max_capacity: The max_capacity of this TournamentBaseItems.  # noqa: E501
        :type: int
        """

        self._max_capacity = max_capacity

    @property
    def preparation_duration(self):
        """Gets the preparation_duration of this TournamentBaseItems.  # noqa: E501


        :return: The preparation_duration of this TournamentBaseItems.  # noqa: E501
        :rtype: int
        """
        return self._preparation_duration

    @preparation_duration.setter
    def preparation_duration(self, preparation_duration):
        """Sets the preparation_duration of this TournamentBaseItems.


        :param preparation_duration: The preparation_duration of this TournamentBaseItems.  # noqa: E501
        :type: int
        """

        self._preparation_duration = preparation_duration

    @property
    def duration(self):
        """Gets the duration of this TournamentBaseItems.  # noqa: E501


        :return: The duration of this TournamentBaseItems.  # noqa: E501
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this TournamentBaseItems.


        :param duration: The duration of this TournamentBaseItems.  # noqa: E501
        :type: int
        """

        self._duration = duration

    @property
    def created_time(self):
        """Gets the created_time of this TournamentBaseItems.  # noqa: E501


        :return: The created_time of this TournamentBaseItems.  # noqa: E501
        :rtype: str
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time):
        """Sets the created_time of this TournamentBaseItems.


        :param created_time: The created_time of this TournamentBaseItems.  # noqa: E501
        :type: str
        """

        self._created_time = created_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TournamentBaseItems, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TournamentBaseItems):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
